name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pick body path if present
        id: notes
        shell: bash
        run: |
          TAG="${GITHUB_REF_NAME}"
          FILE="RELEASE_NOTES/${TAG}.md"
          if [ -f "$FILE" ]; then
            echo "body_path=$FILE" >> $GITHUB_OUTPUT
          else
            echo "body_path=" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          body_path: ${{ steps.notes.outputs.body_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

